name: Release
on:
  push:
    tags: '*'
env:
  GOTOOLCHAIN: local

jobs:
  build-windows:
    name: Build Windows Assets
    runs-on: windows-latest
    strategy:
      matrix:
        go: ['1.23.x']
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - run: git fetch origin "+${GITHUB_REF}:${GITHUB_REF}"
      shell: bash
      # We update the current tag as the checkout step turns annotated tags
      # into lightweight ones by accident, breaking "git describe".
      # See https://github.com/actions/checkout/issues/882 for details.
    - uses: ruby/setup-ruby@v1
    - run: gem install asciidoctor
    - run: Rename-Item -Path C:\msys64 -NewName msys64-tmp -Force
      # We move the MSYS2 installed for Ruby aside to prevent use of its Git,
      # which does not honour the PATH we set to our built git-lfs binary.
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
    - run: mkdir -p "$HOME/go/bin"
      shell: bash
    - run: set GOPATH=%HOME%\go
    - run: choco install -y InnoSetup
    - run: choco install -y zip
    - run: choco install -y jq
    - run: GOPATH="$HOME/go" PATH="$HOME/go/bin:$PATH" go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo@latest
      shell: bash
    - uses: git-for-windows/setup-git-for-windows-sdk@v1
      with:
        flavor: minimal
      # We install the SDK so as to have access to the msgfmt.exe binary
      # from the GNU gettext package.
    - run: mkdir -p bin/releases
      shell: bash
      # We clear the TMPDIR set for Ruby so mktemp and Go use the same
      # volume for temporary files.
    - run: PATH="$HOME/go/bin:$PATH" GOARCH=amd64 go generate && env -u TMPDIR make && mv git-lfs.exe bin/releases/git-lfs-windows-amd64.exe
      shell: bash
    - uses: actions/upload-artifact@v4
      with:
        name: windows-assets
        path: bin/releases
  build-macos:
    name: Build macOS
    runs-on: macos-latest
    strategy:
      matrix:
        go: ['1.23.x']
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - run: git fetch origin "+${GITHUB_REF}:${GITHUB_REF}"
    - uses: ruby/setup-ruby@v1
    - run: gem install asciidoctor
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
    - run: brew install gettext
    - run: mkdir -p bin/releases
    - run: go generate && go build && mv git-lfs bin/releases/git-lfs-darwin-amd64
      env:
          GOARCH: amd64
    - run: mkdir -p bin/releases/macos/arm64
    - run: go generate && go build && mv git-lfs bin/releases/git-lfs-darwin-arm64
      env:
          GOARCH: arm64
    - uses: actions/upload-artifact@v4
      with:
        name: macos-assets
        path: bin/releases
  build-linux:
    name: Linux Release Assets
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.23.x']
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - run: git fetch origin "+${GITHUB_REF}:${GITHUB_REF}"
    - uses: ruby/setup-ruby@v1
    - run: gem install asciidoctor
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
    - run: sudo apt-get update && sudo apt-get -y install gettext libarchive-tools
      env:
          DEBIAN_FRONTEND: noninteractive
    - run: mkdir -p bin/releases
    - run: go generate && go build && mv git-lfs bin/releases/git-lfs-linux-amd64
      env:
        CGO_ENABLED: 0
    - uses: actions/upload-artifact@v4
      with:
        name: linux-assets
        path: bin/releases
  build-main:
    name: Main Release Assets
    needs:
      - build-windows
      - build-macos
      - build-linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/download-artifact@v4
      with:
        name: windows-assets
        path: windows-assets
    - uses: actions/download-artifact@v4
      with:
        name: macos-assets
        path: macos-assets
    - uses: actions/download-artifact@v4
      with:
        name: linux-assets
        path: linux-assets
    - run: mkdir -p bin/releases
    - run: 'find windows-assets -name "*windows*" -type f | xargs -I{} mv {} bin/releases'
    - run: 'find macos-assets -name "*darwin*" -type f | xargs -I{} mv {} bin/releases'
    - run: 'find linux-assets -name "*linux*" -type f | xargs -I{} mv {} bin/releases'
    - run: script/upload --skip-verify $(git describe)
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
